spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/pos
    username: root
    password: tt



  sql:
    init:
      mode: always


#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: wearealivebbss@gmail.com
#    password:tt
#    protocol: smtp
#    auth: true
#    starttls.enable: true


